### ISSUE TITLE
SystemPrep Not Compatible With FIPS-Mode Instances

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/SystemPrep#103]
SystemPrep script dies in the `awscli` section if system is running in FIPS-mode.
~~~
Running cmd: /usr/bin/python virtualenv.py --python /usr/bin/python /opt/awscli
Traceback (most recent call last):
  File "/usr/tmp/systemprep/awscli-bundle/install", line 138, in <module>
    main()
  File "/usr/tmp/systemprep/awscli-bundle/install", line 128, in main
    create_install_structure(working_dir, opts.install_dir)
  File "/usr/tmp/systemprep/awscli-bundle/install", line 64, in create_install_structure
    _create_virtualenv(location=install_dir, working_dir=working_dir)
  File "/usr/tmp/systemprep/awscli-bundle/install", line 81, in _create_virtualenv
    location))
  File "/usr/tmp/systemprep/awscli-bundle/install", line 44, in run
    p.returncode, cmd, stdout + stderr))
__main__.BadRCError: Bad rc (1) for cmd '/usr/bin/python virtualenv.py --python /usr/bin/python /opt/awscli': Already using interpreter /usr/bin/python
New python executable in /opt/awscli/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /opt/awscli/bin/python - setuptools pip wheel:
  Collecting setuptools
  Downloading setuptools-31.0.1-py2.py3-none-any.whl (477kB)
Unknown hash name: md5
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "virtualenv.py", line 2328, in <module>
    main()
  File "virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "virtualenv.py", line 945, in create_environment
    download=download,
  File "virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/awscli/bin/python - setuptools pip wheel failed with error code 1

Could not install awscli. Quitting...
~~~
Due to MD5 being disabled.

**Comment by lorengordon** [comment]
If you know the workaround, are you submitting a patch? Or at least gonna post the workaround? ;)

**Comment by ferricoxide** [comment]
The "workaround" is to not attempt to install the `awscli` at all. Not much of a workaround as much as "avoid the problem altogether". :stuck_out_tongue_winking_eye:

**Comment by lorengordon** [comment]
[This comment](https://github.com/pypa/pip/issues/4049#issuecomment-261634854) is interesting to me. It seems to indicate that the issue is caused by the utterly ancient version of pip distributed by rhel/centos. Did you try upgrading the pip version, and then running the framework?

`curl https://bootstrap.pypa.io/get-pip.py | python`

Sidenote: you may also want to doublecheck the version of the bootstrapper you are referring to, as the [current version](https://github.com/plus3it/SystemPrep/blob/master/BootStrapScripts/SystemPrep-Bootstrap--Linux.sh#L287) installs the awscli to /opt/aws/cli, not /opt/awscli as indicated by the log... It may also just be that the S3 bucket hasn't been updated with the current version...

**Comment by ferricoxide** [comment]
pip isn't distributed with EL - it's provided via EPEL. That said, I only reported the bug after having already upgraded pip and still encountering the error.

**Comment by lorengordon** [comment]
Try running this before the bootstrapper: `export PIP_INDEX_URL=https://pypi.org/simple/`

**Comment by ferricoxide** [comment]
So I don't have to research it later...

To get sysprep to work on _RHEL_ 7 (when the AMI has been customized to launch instances in FIPS-mode), need to:
- Ensure that the `epel` repo is active:
  - The `python-boto` package included in the `rhui-REGION-rhel-server-rh-common` does not seem to be importable and will cause the `bootstrap.py` to fail
  - Need it active so the `python-pip` RPM is installable (so that any `pip`-related tasks won't fail)
- Once the `python-pip` RPM is installed, probably want to run `PIP_INDEX_URL=https://pypi.org/simple/ ; pip install --upgrade pip` to ensure that `pip` is a good/recent version and pointed to the FIPS-compatible index (upgrading `pip` fixes the index-URL, but, to install it, you have to temp-set the env)

**Comment by ferricoxide** [comment]
With pending deprecation of systemprep (in favor of Watchmaker) — and decision to declare systemprep not supported for EL7 — am closing this issue.
