### ISSUE TITLE
Quickstart from a Linux terminal doesn't work as written in Readme

### ISSUE THREAD

**Issue by rbdunne** [plus3it/SystemPrep#90]
We were following the Quick Start guide for setting up linux instance from the command line. However If you do this the instance it brings up becomes unreachable shortly after the salt kicks in.

Here is what we think is happening. (I'm pasting this in from one of our developers notes)
The instance will come up but eventually becomes inaccessible. We were able to track this down to changes that systemprep makes to iptables that effectively block all traffic to the instance.

The instance appears to have a reasonable set of default iptables rules in /etc/sysconfig/iptables that allow certain types of traffic like SSH through so that the it is actually possible to log into the instance. However, when the instance first comes up, iptables is not loaded into memory. This means none of the rules in the file are actually active. There are some salt formulas applied by systemprep that make changes to iptables.

One formula identified as cat2/V38512.sls ensures iptables is installed and then saves the current set of rules in memory to /etc/sysconfig/iptables before making further modifications. The problem is that there are no rules in memory so it effectively wipes out the existing set of rules in that file. A subsequent salt formula identified as cat2/V38513.sls then goes on to set the default policy for the INPUT chain to DROP. It will also add some rules allow logging in to the machine. However, these rules are only added if /etc/sysconfig/iptables does not already exist. In our case it does, thus the instance becomes inaccessible.

**Comment by ferricoxide** [comment]
The states are currently tracked in the plus3it/ash-linux-formula project. Last content-update to the states referenced in this issue appears to be the April 13, 2015 updates (at or about commit plus3it/ash-linux-formula@593eb2069325d8b081997739a5d3df3936a03959).

**Comment by lorengordon** [comment]
@rbdunne, thanks for the report. We'll take a look. Can you let us know which AWS region and AMI you were using?

**Comment by lorengordon** [comment]
@rbdunne, I'm not able to duplicate this. I am seeing that systemprep runs, reboots the instance, and then the instance is available via ssh on port 22 once the reboot completes. Can you provide more details on your exact steps?

**Comment by rbdunne** [comment]
We copy pasted the Quick Start directions exactly as they are listed in the Readme. As you can see below we used us-east-1 and it grabbed an ami based on the pattern. (We were doing this about 2 weeks ago. We have since terminated the instances so I can't tell you exactly what ami was used at that time) If we logged into the machine before salt could run and reload the iptables rules in advance then we could prevent this problem from occurring.

userdata="https://s3.amazonaws.com/systemprep/BootStrapScripts/SystemPrep-Bootstrap--Linux.sh"
region="us-east-1"
amipattern="RHEL-6.7_HVM_GA-*-x86_64-1-Hourly2-GP2"
ami=$(aws ec2 describe-images --region $region --filters Name="name",Values="$amipattern" --query 'Images[0].ImageId' --out text)

aws ec2 run-instances \
--image-id $ami \
--user-data $userdata \
--key-name $key \
--security-group-ids $sg \
--instance-type t2.micro \
--associate-public-ip-address \
--region $region

**Comment by lorengordon** [comment]
Interesting, I can duplicate the problem when using the RedHat AMI resulting from that query (`ami-0d28fe66`), but two other AMIs I've tested work fine (one private, the other is the CentOS 6 AMI on the MarketPlace - `ami-1c221e76`). I'll dig into this more tomorrow to figure out the logic flaw.

**Comment by ferricoxide** [comment]
@rbdunne Looks like you won the RHEL update sweepstakes: RHEL 6.8 released on the 19th and the RHUI repos were updated a day or so later. Our main testing-platform - CentOS 6 - hasn't been updated to 6.8, yet (probably a few weeks out if they follow previous patterns).

Please reference plus3it/ash-linux-formula#143 to track our progress on this issue. My intention is to tackle it within the next forty-eight hours.

**Comment by lorengordon** [comment]
@rbdunne, please take a look at https://github.com/plus3it/ash-linux-formula/pull/145 for the proposed fix. Feel free to comment there if you have any feedback on the approach.

**Comment by rbdunne** [comment]
@lorengordon, while we used a slightly different approach as our workaround, your logic looks sound to us and seems like a good fix. Thanks for the quick response.

**Comment by lorengordon** [comment]
@rbdunne, no problem, thanks again for the report. The fix for this issue is now live, but you will still run into the problem @ferricoxide linked to, regarding RHEL 6.8. Stay tuned for that patch as well. Please let us know if you have any other problems!

**Comment by lorengordon** [comment]
@rbdunne, fyi, the [fix for the issue with EL6.8](https://github.com/plus3it/ash-linux-formula/pull/148) just went live. The SystemPrep Quick Start should now run through to completion.
