### ISSUE TITLE
Update RootCertUrl?

### ISSUE THREAD

**Issue by KevinPlus3** [plus3it/SystemPrep#94]
Currently, in the PowerShell bootstrap script, a variable ($RootCertUrl) is bound that takes a type of String. However, the Install-RootCerts function allows for a list of strings to be passed in and it will iterate through each string allowing for retrieving certs from various hosts.

Should the bound variable be updated to allow for a list of string to be passed and thus passed on to the function?  Or shall we just ignore this minor discrepancy, i.e. the function can handle the list of strings but the script itself only allows for one host to be passed in?

**Comment by lorengordon** [comment]
@KevinPlus3, perhaps we can make that change on watchmaker. We don't really have a use case for passing in multiple cert hosts at this time, and we're trying to minimize changes to SystemPrep to those with immediate user impact.
